### ISSUE TITLE
你好，咨询代码

### ISSUE THREAD

**Issue by Adidas-okkk** [Jesse54211/ysms-vue#1]
代码的验证码模块有点问题，请问有时间帮帮我吗，谢谢

**Comment by Jesse54211** [comment]
> 代码的验证码模块有点问题，请问有时间帮帮我吗，谢谢

验证码？？你没启动后端吧，你去gitee看吧，前后端我上传gitee了

**Comment by Adidas-okkk** [comment]
> > 代码的验证码模块有点问题，请问有时间帮帮我吗，谢谢
> 
> 验证码？？你没启动后端吧，你去gitee看吧，前后端我上传gitee了

好，我去看看，可以加个联系方式吗，有问题咨询您？

**Comment by Jesse54211** [comment]
> > > 代码的验证码模块有点问题，请问有时间帮帮我吗，谢谢
> > 
> > 
> > 验证码？？你没启动后端吧，你去gitee看吧，前后端我上传gitee了
> 
> 好，我去看看，可以加个联系方式吗，有问题咨询您？

qq542119880
